### ISSUE TITLE
Messed up string fomatting for "3.14"

### ISSUE THREAD

**Issue by francisdb** [BenFradet/vscode-unison#33]
I guess the decimal number literal formatting messes up some things?

<img width="723" alt="image" src="https://user-images.githubusercontent.com/161305/80714774-aea6a980-8af5-11ea-95fc-d1a887d65267.png">

**Comment by BenFradet** [comment]
yes with the current grammar there are issues with numbers, they are being worked on in https://github.com/unisonweb/unison-tmLanguage

**Comment by BenFradet** [comment]
The goal is to pull the grammar from there so it might be better logging issues regarding the grammar directly in that repo.

**Comment by francisdb** [comment]
will move these over there

**Comment by francisdb** [comment]
moved to https://github.com/unisonweb/unison-tmLanguage/issues/35
